version: "3.9"
services:
  postgres-db:
    image: postgres:15.5-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.4.9
    container_name: healenium
    restart: on-failure
    depends_on:
      - postgres-db
    ports:
      - "7878:7878"
    environment:
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
      - SPRING_POSTGRES_DB_HOST=postgres-db
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=true
      - HLM_LOG_LEVEL=info
    volumes:
      - ./logs/:/logs
      - ./screenshots/:/screenshots
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.5
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healenium

networks:
  healenium:
    name: healenium
